name: Build ExpressLRS
on:
  push:
    tags:
      - '*.*.*'
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.target }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install wheel

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Run PlatformIO Tests
      run: |
        platformio platform install native
        platformio platform update
        cd src
        PLATFORMIO_BUILD_FLAGS="-DRegulatory_Domain_ISM_2400" pio test -e native

  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Validate target files
      run: |
        cd src
        python python/targets_validator.py

  release:
    needs: [validation, test]
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.create-release.outputs.id }}
    steps:
      - name: create empty release
        if: startsWith(github.event.ref, 'refs/tags/')
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: 'ExpressLRS Unified Firmwares v${GITHUB_REF#refs/*/}'
          tag_name: ${GITHUB_REF#refs/*/}
          body: 'Unified target firmware release.'
          draft: true

  targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-targets.outputs.targets }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: set-targets
      run: echo "::set-output name=targets::[$( (grep "\[env:.*UART\]" src/targets/unified.ini ; grep -r "\[env:.*STLINK\]" src/targets/) | sed 's/.*://' | sed s/.$// | egrep "(STLINK|UART)" | grep -v DEPRECATED | tr '\n' ','  | sed 's/,$/"\n/' | sed 's/,/","/'g | sed 's/^/"/')]"
      
  build:
    needs: [targets, release]
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(needs.targets.outputs.targets)}}
    runs-on: ubuntu-latest
    steps:

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.target }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install wheel

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Run PlatformIO
      run: |
        platformio platform update
        platformio platform install native
        mkdir -p ~/artifacts/firmware
        cd src
        case ${{matrix.target}} in
          *2400* | FM30*)
            # release builds
            PLATFORMIO_BUILD_FLAGS="-DRegulatory_Domain_EU_CE_2400" pio run -e ${{ matrix.target }}
            OUTDIR=~/artifacts/firmware/LBT/`echo ${{ matrix.target }} | sed s/_via.*//`
            mkdir -p $OUTDIR
            mv .pio/build/${{ matrix.target }}/firmware.{elrs,bin} $OUTDIR >& /dev/null || :

            PLATFORMIO_BUILD_FLAGS="-DRegulatory_Domain_ISM_2400" pio run -e ${{ matrix.target }}
            OUTDIR=~/artifacts/firmware/FCC/`echo ${{ matrix.target }} | sed s/_via.*//`
            mkdir -p $OUTDIR
            mv .pio/build/${{ matrix.target }}/firmware.{elrs,bin} $OUTDIR >& /dev/null || :
            ;;
          *)
            # release build
            PLATFORMIO_BUILD_FLAGS="-DRegulatory_Domain_FCC_915" pio run -e ${{ matrix.target }}
            OUTDIR=~/artifacts/firmware/FCC/`echo ${{ matrix.target }} | sed s/_via.*//`
            mkdir -p $OUTDIR
            mv .pio/build/${{ matrix.target }}/firmware.{elrs,bin} $OUTDIR >& /dev/null || :
            ;;
        esac
        # copy the common ESP32 files
        if [[ ${{matrix.target}} == *ESP32* ]] ; then
          cp ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/bin/bootloader_dio_40m.bin ~/artifacts/firmware/
          cp ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin ~/artifacts/firmware/
          mv .pio/build/${{ matrix.target }}/partitions.bin ~/artifacts/firmware/
        fi

    - name: Store Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: firmware
        path: ~/artifacts/**/*
      continue-on-error: true

  firmware:
    needs: [build, validation, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get firmware artifacts
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: dist

      - name: Copy hardware files to firmware folder
        run: cp -r src/hardware dist/firmware

      - name: Copy bootloader files to firmware folder
        run: cd src ; find bootloader -name \*.bin -o -name \*.frk | grep -v src/ | cpio -pdm ../dist/firmware

      - name: Update firmware artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: dist/**/*

      - name: Upload firmware to release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_id: ${{ needs.release.outputs.id }}
          file: dist/firmware/*

  installer:
    needs: [validation, test]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - run: pip install pyserial
      - run: pip install pyinstaller
      - run: pyinstaller -F src/python/binary_configurator.py -n installer-${{ matrix.os }}

      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: dist/*